version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - pip install .[rtd] --extra-index-url=https://${NETSQUIDPYPI_USER}:${NETSQUIDPYPI_PWD}@pypi.netsquid.org



python:
   install:
     - method: pip
       path: .
       extra_requirements:
         - rtd
     - method: pip
       path: package

